let strip = neopixel.create(DigitalPin.P0, 20, NeoPixelMode.RGB)
let range1 = strip.range(0, 5)
let range2 = strip.range(5, 5)
let range3 = strip.range(10, 5)
let range4 = strip.range(15, 5)
basic.forever(function () {
    range1.showColor(neopixel.colors(NeoPixelColors.Red))
    range2.showColor(neopixel.colors(NeoPixelColors.Purple))
    range3.showColor(neopixel.colors(NeoPixelColors.Blue))
    range4.showColor(neopixel.colors(NeoPixelColors.Green))
    basic.pause(500)
    strip.showColor(neopixel.colors(NeoPixelColors.Black))
    basic.pause(500)
})
